### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Hellowlol** [turbokongen/hass-AMS#23]
- [x] go async PR #27
- [x] sniff the serial data and set the parser automatically PR #25
- [ ] improve logging
- [x] bring back yaml. (Many users prefer yaml, like me) PR #20
- [x] restore last known states PR #24

I can help out with this.

**Comment by JLFN** [comment]
How many sensors should i get? this is the info for mine HAN.

**Comment by turbokongen** [comment]
That looks perfect 👌🏻 14 is max number of sensors for 3phase meters.
